### ISSUE TITLE
Equation 6 question

### ISSUE THREAD

**Issue by bpbond** [PNNL-TES/millenial#12]
```fortran
 791 	! SOILAGG -> MINERAL
 792 	if (SOILAGG > 0._r8) then
 793         f_SO_break = SOILAGG * kagg * t_scalar * w_scalar
 794 	f_SO_PO_break = f_SO_break * 1.5 / 3.
 795 	f_SO_MI_break = f_SO_break * 1.5 / 3.
 796 	end if
```
Just out of curiosity, why `1.5 / 3.`? 🤷‍♂️

**Comment by email-clm** [comment]
Sorry for this, they were originally set to 1/3 + 2/3, calibrated to 2/3 +
1/3, later found 1/2 is best, during calibration it was set to 1.5 / 3. the
code was not cleaned for the final version.
Thanks for the work porting to R, it makes me rethink/recheck all codes, I
will definitely reformat all codes to ensure high readability.

Xiaofeng

**Comment by bpbond** [comment]
Ha, good to know, thanks!
