### ISSUE TITLE
Call Fortran subroutines directly from R?

### ISSUE THREAD

**Issue by ashiklom** [PNNL-TES/millenial#6]
There are good reasons to port the entire model into R, and shouldn't take a _ton_ of work since the model seems relatively small and simple.

But taking a quick peek at the model structure, I just wanted to point out that you might be able to save yourselves some work by calling some of the underlying subroutines from R via the `.Fortran` function. Because the subroutines seem reasonably self-contained, I think this should work almost out of the box.

For example, you can call the `soilpsi` subroutine via:

```
sand <- 60
clay <- 35
silt <- 5
# etc...
# Pre-allocate output vectors
psisat <- numeric(1)
psi <- numeric(1)
smp_l <- numeric(1)
results <- .Fortran("soilpsi", sand, clay, silt, vwc, vwcsat, organic, psisat, psi, smp_l)
# `results` is a list containing all the inputs
# therefore, something like this should work.
psisat_out <- results[[8]]
psi_out <- results[[9]]
smp_l <- results[[10]]
```

Just an FYI. If nothing else, this could be a useful way to check your work to make sure the R version produces the same results as the Fortran original.

A real life example of this is the [PEcAnRTM package](https://github.com/PecanProject/pecan/tree/develop/modules/rtm) -- all the RTMs are written in Fortran, and the package provides an R interface. For instance, here is the [R code](https://github.com/PecanProject/pecan/blob/develop/modules/rtm/R/prospect.R#L18-L50) for the PROSPECT model, and the corresponding [Fortran code](https://github.com/PecanProject/pecan/blob/develop/modules/rtm/src/RTM/prospect/prospect.D.f90#L43-L58).

**Comment by bpbond** [comment]
Thanks very much @ashiklom . I did think about this, but decided there are some reasons–most of which you enumerate above–that it worth just biting the bullet and bringing it into R. But much appreciated–I've only used `.Fortran` once or twice, and it would fun to play with it more sometime.
