### ISSUE TITLE
NPP allocation question

### ISSUE THREAD

**Issue by bpbond** [PNNL-TES/millenial#8]
The text of Abramoff et al. (2017) says:

>The change in POM (P) stock with time is governed by the balance between plant C input and aggregate C breakdown, aggregate C formation, and decomposition,
>dP/dt = piFi  + paFa - Fpa - Fpl  [1]
>where Fi is aboveground plant litter, root litter and root exudates, pi is the proportion of C input allocated to POM (**1/3 of inputs to POM and 2/3 of inputs to LMWC** after Oleson et al. 2013)

But in the code:
```fortran
 807 	LMWC = LMWC + (f_PO_LM_dep + f_MI_LM_des - f_LM_leaching - f_LM_MI_sor - f_LM_MB_uptake - temp2) + forc_npp / 3.
 808 	
 809 	POM = POM + (f_SO_PO_break - f_PO_LM_dep - f_PO_SO_agg) + forc_npp * 2. / 3.
```

I.e. it looks like 2/3 of NPP is going to POM, and 1/3 to LMWC. Is this discrepancy intentional? If not which is correct? Thanks.

**Comment by rabramoff** [comment]
Oh good catch - the sentence is written wrong but equation 1 is right. pi is defined in Table 3 as 2/3 so piFi -> 2/3 of Fi to POM, and Fi(1-pi) -> is 1/3 of Fi to LMWC in equation 7.

**Comment by bpbond** [comment]
OK good thanks!
